export const CMD = {
  CAR_INTEGRATION_CREATED: 'car_integration_created_event',
  CAR_INTEGRATION_UPDATED: 'car_integration_updated_event',
  CAR_NOTIFICATION: 'car_notification_event',
  CARZ_NOTIFICATION_GROUP_EVENT: 'car_notification_group_event',
  CARZ_APPOINTMENT_REMIND: 'carz_remind_event',
  CAR_INTEGRATION_VIEW: 'car_integration_view_event',
  CAR_INTEGRATION_FAVORITE: 'car_integration_favorite_event',
  CAR_INTEGRATION_BRAND_CREATED: 'car_integration_brand_created_event',
  CAR_INTEGRATION_BRAND_UPDATED: 'car_integration_brand_updated_event',
  CAR_LOYALTY_IMPORT_VOUCHER_CODE: 'car_loyalty_import_voucher_code',
  CAR_LOYALTY_ROLLBACK_VOUCHER: 'car_loyalty_rollback_voucher',
  CAR_LOYALTY_ACCUMULATION: 'car_loyalty_accumulation',
  PRODUCT_INTEGRATION_CREATED: 'product_integration_created_event',
  PRODUCT_INTEGRATION_UPDATED: 'product_integration_updated_event',
  PRODUCT_INTEGRATION_ADDRESS_UPDATED: 'product_integration_address_updated',
  CAR_PART_CAR_STORE_CREATED: 'car_part_car_store_created',
  CAR_PART_CAR_STORE_UPDATED: 'car_part_car_store_updated',
  MERCHANT_ACCOUNT_REMOVED: 'merchant_account_removed',
  CAR_INTEGRATION_MODEL_INSERTED: 'car_integration_model_inserted_event',
  PUSH_NOTIFICATION_BY_DEVICE: 'push_noti_by_device',
  PUSH_NOTIFICATION_NORMAL: 'push_noti_normal',
  // RECOMMENDATION
  RECOMMENDATION_INSERT_SEARCH: 'recommendation_insert_search',
  RECOMMENDATION_BULK_BY_USER: 'recommendation_bulk_by_user',
  // CRAWLER
  CAR_CRAWLER_CARZ_CREATED: 'car_crawler_carz_created',
};
