export const SERVICES = {
  CARZ_INTEGRATIONS: 'CARZ_INTEGRATIONS',
  CARZ_NOTIFICATIONS: 'CARZ_NOTIFICATIONS',
  CARZ_COMMUNICATIONS: 'CARZ_COMMUNICATIONS',
  CARZ_LOYALTIES: 'CARZ_LOYALTIES',
  CARZ_CAR_PARTS: 'CARZ_CAR_PARTS',
  CARZ_SUBSCRIPTIONS: 'CARZ_SUBSCRIPTIONS',
};
